add 'map::clear()', 'map::has()', 'map::insert()', 'map::set()' convenience methods
zetzit/zz pull request #131
Opened 2020-09-24 14:21 UTC by jwerle

2020-09-24 14:26 UTC, aep requested changes

2020-09-24 14:26 UTC, aep commented on modules/map/src/lib.zz
> +export fn clear(Map mut *self) bool {
this can't fail. no need to return bool

2020-09-24 14:26 UTC, aep commented on modules/map/src/lib.zz
> +  if 0 != self->get(key) {
duplicated call to get()

2020-09-24 14:35 UTC, aep commented on modules/map/src/lib.zz
> +    self->remove(it.key.mem);
actually, this should probably avoid rehashing the keys.

look at remove_slk for iterating the internal structure

2020-09-25 08:52 UTC, aep commented
@jwerle  in line with #132 i believe insert should copy while set does borrow
i.e. the naming convention is "the more forceful verb does a copy"

2020-09-25 10:40 UTC, jwerle commented
Makes sense!

2020-09-25 10:53 UTC, jwerle commented
Still working on this! Should have out this morning

2020-09-25 17:16 UTC, aep approved these changes
nice, just nitpicks from here

2020-09-25 17:16 UTC, aep commented on modules/map/src/main.zz
> +    err::assert(amap.count() == 0);
could you add a test please that checks that the pool memory has been returned?

i.e. compare pool::free_bytes()

2020-09-25 17:16 UTC, aep commented on modules/map/src/lib.zz
> +/// Clear all references for all keys in the `Map`.
needs to be clear that it frees all keys and all values,
at which point any borrows to them are no longer valid

2020-09-25 17:52 UTC, aep commented on modules/map/src/main.zz
> +    let free_bytes_after_clear = free_bytes + (amap.count() * sizeof(A));
aye, thats exactly the bug i wanted to catch with the test.
if it equals (amap.count() * sizeof(A)), it didn't free the internal Node structure.
so something is wrong with i_dealloc.

2020-09-25 17:54 UTC, aep commented on modules/map/src/main.zz
> +    let free_bytes_after_clear = free_bytes + (amap.count() * sizeof(A));
yup, i_dealloc doesnt actually free the node.

would you like to fix this or merge the PR and leave it to me?

2020-09-25 18:13 UTC, jwerle commented on modules/map/src/main.zz
> +    let free_bytes_after_clear = free_bytes + (amap.count() * sizeof(A));
i'll take a look!

2020-09-25 19:00 UTC, aep commented on modules/map/src/main.zz
> +        let mut nodesize = pool::align(unsafe<usize>(sizeof(map::Node)));
smart idea to use align here to make sure it matches the overhead of pool

2020-09-25 19:38 UTC, jwerle commented on modules/map/src/main.zz
> +        let mut nodesize = pool::align(unsafe<usize>(sizeof(map::Node)));
seemed like the right thing to do!

2020-09-26 08:25 UTC, aep commented
lgtm thanks

2020-09-26 08:25 UTC, merged